[CHORE] vite, tailwind 설치
CarSpotterHQ/client pull request #6
Opened 2024-11-14 13:08 UTC by youngryul

vite 5.4.9 버전
streaming
typescript
tailwindcss 3.4.14 버전

2024-11-14 14:43 UTC, 1eeyerin requested changes
tailwind 기본 셋팅이 안되어있어서 확인 부탁드릴게요!
https://tailwindcss.com/docs/installation

2024-11-14 14:43 UTC, 1eeyerin commented on src/App.css
> +#root {
해당 파일 제거 해주시면 좋을 것 같습니다!

2024-11-14 14:43 UTC, 1eeyerin commented on src/Card.tsx
> +      <button onClick={() => setCount((count) => count + 1)}>
동일합니다!

2024-11-14 14:43 UTC, 1eeyerin commented on src/index.css
> +button {
동일합니다!

2024-11-21 11:25 UTC, youngryul commented
추가 적용했습니다!!

2024-11-21 12:32 UTC, bohodays approved these changes

2024-11-22 04:40 UTC, 1eeyerin approved these changes

2024-11-22 04:45 UTC, youngryul commented
예린님이 수정하신 사항까지 해서 merge 하겠습니다.

2024-11-22 04:45 UTC, merged